# scrutinizer-ci.com configuration
imports:
    - javascript
    - php
filter:
    excluded_paths: [js/vendor/*]
checks:
    javascript: true
    php: true
build:
    nodes:
        test:
            environment:
                php: 7.1
                node: 8
            dependencies:
                before:
                    - composer install
                    - composer require tecnickcom/tcpdf pragmarx/google2fa-qrcode samyoul/u2f-php-server
            tests:
                override:
                    - php-scrutinizer-run
